gage_number: "03020500"
site_name: "OilCreek"

# Base folder (you can keep this absolute since this is your machine)
base_folder: "C:/Users/WeisA/Documents/Oil_Creek/USGS"

# Full project folder path (now explicitly defined)
project_folder: "${base_folder}/${gage_number}_${site_name}"

# Folder structure (names only — folder_setup will build full paths using project_folder)
folders:
  daily_qw: "Daily/Qw"
  inst_qw: "Inst/Qw"
  inst_hw: "Inst/Hw"
  breakup_events: "BreakupEvents"
  plots: "Plots"
  stats: "Stats"
  processed_data: "ProcessedData"
  logs: "Logs"

# Date windows
winter_season:
  start: "11-01"
  end: "03-31"

breakup_event_window:
  days_before: 5
  days_after: 5

# Available data ranges
available_dates:
  daily_streamflow: ["1932-10-01", "2025-02-28"]
  inst_streamflow: ["1986-10-01", "2025-02-28"]
  inst_gageheight: ["2007-10-01", "2025-02-28"]

# Breakup event dates file (directly tied to project_folder)
breakup_dates_file: "${project_folder}/${folders.breakup_events}/Event_Dates.txt"

# Plotting preferences
plot_settings:
  font: Arial
  fontsize: 12
  title_fontsize: 14
  dpi: 600
  figure_size:
    width: 12
    height: 6
  colors:
    daily: black
    inst: red
    gage_height: blue
  linestyle:
    daily: "--"
    inst: "-"
    gage_height: "-"

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
